//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTime.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropDataType
    {
        public string Data { get; set; }
        public int PropID { get; set; }
        public int ID { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
