//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONPROC_MAIN_FILTER_N
    {
        public int NUM_USER { get; set; }
        public Nullable<System.DateTime> DTBEFORE { get; set; }
        public Nullable<System.DateTime> DTAFTER { get; set; }
        public string EXECUTOR { get; set; }
        public Nullable<int> NUM_OBJECT { get; set; }
        public Nullable<int> NUM_PARAM { get; set; }
        public Nullable<int> NUM_METH { get; set; }
        public Nullable<int> NUM_ALGTYPE { get; set; }
        public Nullable<int> NUM_ALGGROUP { get; set; }
        public Nullable<int> POSX { get; set; }
        public Nullable<int> POSY { get; set; }
        public Nullable<int> SIZEX { get; set; }
        public Nullable<int> USELAST { get; set; }
        public string ALG_VER { get; set; }
        public string NAME_ALG { get; set; }
        public string NAME_GROUP { get; set; }
    }
}
