//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFORMSDOXP
    {
        public int NUM_REC { get; set; }
        public Nullable<int> NUM_DOX_FORM { get; set; }
        public string NAME_P { get; set; }
        public string VALUE_P { get; set; }
    }
}
