//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFORMSDOX
    {
        public Nullable<int> NUM_DOC { get; set; }
        public int NUM_REC { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> TM { get; set; }
        public byte[] DOC { get; set; }
        public Nullable<int> FINAL { get; set; }
        public string FIO_ID { get; set; }
        public Nullable<int> LAB_ID { get; set; }
    }
}
