//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOPLINK
    {
        public int NUM_REC { get; set; }
        public string TBL1 { get; set; }
        public string FLD1 { get; set; }
        public Nullable<short> RELT1T2 { get; set; }
        public string TBL2 { get; set; }
        public string FLD2 { get; set; }
    }
}
