//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVFIELD
    {
        public Nullable<int> NUM_INV { get; set; }
        public int NUM_REC { get; set; }
        public string NAME { get; set; }
        public string FIELD { get; set; }
        public Nullable<short> TYPE { get; set; }
    }
}
