//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LAB()
        {
            this.JRO_LAB = new HashSet<JRO_LAB>();
        }
    
        public int NUM_LAB { get; set; }
        public string NAME_LAB { get; set; }
        public string LAB_MNGR_JOB { get; set; }
        public string LAB_MNGR { get; set; }
        public string METROLOG { get; set; }
        public string ATTESTAT { get; set; }
        public string ADDRESS { get; set; }
        public string PHONES { get; set; }
        public string LAB1 { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JRO_LAB> JRO_LAB { get; set; }
    }
}
