//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LJ
    {
        public int NUM_REC { get; set; }
        public string JOURNAL { get; set; }
        public string FORMULABEFORE { get; set; }
        public string FORMULAAFTER { get; set; }
        public string SHORTNAME { get; set; }
        public string INSTRUCTION { get; set; }
        public Nullable<bool> NORCHECK { get; set; }
        public Nullable<bool> NOXMED { get; set; }
        public Nullable<bool> USE_GR { get; set; }
        public Nullable<bool> FULLSCR { get; set; }
        public Nullable<bool> BRAKSCAN { get; set; }
        public Nullable<int> NUM_N_SHOW { get; set; }
        public Nullable<bool> USE_REGNUM { get; set; }
        public Nullable<int> REGNUM { get; set; }
        public Nullable<bool> USE_REAGENT_WRITEOFF { get; set; }
        public Nullable<bool> USEMETHLAB { get; set; }
        public Nullable<int> VIEWTYPE { get; set; }
        public Nullable<bool> STOREFILES { get; set; }
        public string CLAS { get; set; }
        public Nullable<int> NUMB { get; set; }
        public string SHORTJOURNAL { get; set; }
        public string FBEFOREDESC { get; set; }
        public string FAFTERDESC { get; set; }
        public Nullable<int> NUMTEXTDOC { get; set; }
        public string CIPHERFIELD { get; set; }
        public Nullable<bool> MNGPARAMS { get; set; }
        public byte[] DOCVIS { get; set; }
        public Nullable<bool> USE_VERIF { get; set; }
        public Nullable<double> VERIFKOEF { get; set; }
        public string DATETAKENTXT { get; set; }
        public string TIMETAKENTXT { get; set; }
        public Nullable<bool> ISDTSHOW { get; set; }
        public Nullable<bool> ISLOCKINSERT { get; set; }
        public Nullable<bool> COPYTAKINGDTTM { get; set; }
        public Nullable<int> NUM_C_CM { get; set; }
        public Nullable<bool> USEMULTIINS { get; set; }
        public Nullable<bool> USE_SELECTNORM { get; set; }
    }
}
