//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LJ_LOCKF
    {
        public int NUM_REC { get; set; }
        public Nullable<int> NUM_LJT { get; set; }
        public Nullable<int> NUM_N { get; set; }
        public Nullable<int> NUM_FIO1 { get; set; }
        public Nullable<int> NUM_FIO2 { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> TM { get; set; }
    }
}
