//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGIN()
        {
            this.LOGIN_RIGHTS = new HashSet<LOGIN_RIGHTS>();
        }
    
        public int NUM_REC { get; set; }
        public string UZER { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> LAB { get; set; }
        public string comment { get; set; }
        public Nullable<int> OKT { get; set; }
        public string FIOISP { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<int> HIM_RIGHT { get; set; }
        public Nullable<int> UNI_RIGHT { get; set; }
        public Nullable<int> DOC_RIGHT { get; set; }
        public Nullable<short> JUR_RIGHT { get; set; }
        public Nullable<short> SML_RIGHTS { get; set; }
        public Nullable<int> OTHER_RIGHTS { get; set; }
        public Nullable<int> SMK_RIGHTS { get; set; }
        public string MNG_RIGHTS { get; set; }
        public Nullable<int> LAB_RIGHTS { get; set; }
        public Nullable<int> WORK_SP { get; set; }
        public Nullable<int> TJ_RIGHTS { get; set; }
        public Nullable<int> OTHER_RIGHTS2 { get; set; }
        public Nullable<int> NUM_IMG { get; set; }
        public Nullable<int> PASS_PER { get; set; }
        public Nullable<System.DateTime> PASS_END { get; set; }
        public string HIM2_RIGHTS { get; set; }
        public Nullable<bool> BLOCKED { get; set; }
        public string JRO2_RIGHTS { get; set; }
        public string ADUSER { get; set; }
        public Nullable<int> worker_rights { get; set; }
        public string other_rights3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN_RIGHTS> LOGIN_RIGHTS { get; set; }
    }
}
