//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_RIGHTS
    {
        public int NUM_REC { get; set; }
        public Nullable<int> NUM_LOGIN { get; set; }
        public Nullable<int> NUM_IGROUPS { get; set; }
        public Nullable<bool> RIGHTS { get; set; }
    
        public virtual IGROUP IGROUP { get; set; }
        public virtual LOGIN LOGIN { get; set; }
    }
}
