//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class METHPARVAR
    {
        public Nullable<int> NUM_PRM { get; set; }
        public int NUM_REC { get; set; }
        public string VARIABLE { get; set; }
        public string V2 { get; set; }
        public string DESCR { get; set; }
        public string UNIT { get; set; }
        public Nullable<double> CONSTANT { get; set; }
        public Nullable<double> MAXVAL { get; set; }
        public string CALIBR { get; set; }
        public Nullable<double> MINVAL { get; set; }
        public Nullable<bool> ISMETROL { get; set; }
        public Nullable<int> NUM_JPR { get; set; }
        public Nullable<int> NUM_MTD { get; set; }
        public Nullable<bool> CONST_LOCK { get; set; }
        public Nullable<bool> IS_LEFT { get; set; }
        public Nullable<int> NUM_JRPV { get; set; }
        public Nullable<bool> COPY_LOCK { get; set; }
        public Nullable<int> NUM_QUERY { get; set; }
        public Nullable<int> NUM_CALC { get; set; }
        public Nullable<bool> ISVSP { get; set; }
        public Nullable<int> NUM_JPR2 { get; set; }
        public Nullable<int> NUM_CRM { get; set; }
        public Nullable<bool> ISRAZB { get; set; }
    }
}
