//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMK2_JFORMS
    {
        public int NUM_REC { get; set; }
        public Nullable<int> NUM_SMK { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public string INSTRUCTION { get; set; }
        public Nullable<bool> USECONFIRM { get; set; }
    }
}
