//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPR_HEADERS
    {
        public int NUM_REC { get; set; }
        public string SID { get; set; }
        public string NAMEFORM { get; set; }
        public string COMM { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> NUM_GROUP { get; set; }
        public Nullable<int> LIMITTXT { get; set; }
    }
}
