//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTypeProp
    {
        public int ID { get; set; }
        public int TaskTypeID { get; set; }
        public int PropID { get; set; }
    
        public virtual TaskType TaskType { get; set; }
        public virtual Property Property { get; set; }
    }
}
