//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagmentDBEntities : DbContext
    {
        public TaskManagmentDBEntities()
            : base("name=TaskManagmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttrValue> AttrValues { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropValue> PropValues { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskTypeProp> TaskTypeProps { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTask> UserTasks { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<WorkTypeAttr> WorkTypeAttrs { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
        public virtual DbSet<CONPROC_MAIN_FILTER_N> CONPROC_MAIN_FILTER_N { get; set; }
        public virtual DbSet<DFATT> DFATTs { get; set; }
        public virtual DbSet<DFORM> DFORMS { get; set; }
        public virtual DbSet<DFORMSDOX> DFORMSDOXes { get; set; }
        public virtual DbSet<DFORMSDOXATT> DFORMSDOXATTs { get; set; }
        public virtual DbSet<DFORMSDOXP> DFORMSDOXPs { get; set; }
        public virtual DbSet<DFORMSHISTORY> DFORMSHISTORies { get; set; }
        public virtual DbSet<DFORMSOLE> DFORMSOLEs { get; set; }
        public virtual DbSet<DFORMSQUERY> DFORMSQUERies { get; set; }
        public virtual DbSet<DOPLINK> DOPLINKS { get; set; }
        public virtual DbSet<GLOBALOPTION> GLOBALOPTIONS { get; set; }
        public virtual DbSet<IGLIST> IGLISTs { get; set; }
        public virtual DbSet<IGROUP> IGROUPS { get; set; }
        public virtual DbSet<INVENT> INVENTS { get; set; }
        public virtual DbSet<INVFIELD> INVFIELDS { get; set; }
        public virtual DbSet<JOURNAL> JOURNALs { get; set; }
        public virtual DbSet<JRO_LAB> JRO_LAB { get; set; }
        public virtual DbSet<LAB> LABS { get; set; }
        public virtual DbSet<LEVEL> LEVELS { get; set; }
        public virtual DbSet<LJ_LOCKF> LJ_LOCKF { get; set; }
        public virtual DbSet<LJ> LJS { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<LOGIN_CLJJ_RIGHTS> LOGIN_CLJJ_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_CLJL_RIGHTS> LOGIN_CLJL_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_JGROUP_RIGHTS> LOGIN_JGROUP_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_JRO_RIGHTS> LOGIN_JRO_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_JUHR_RIGHTS> LOGIN_JUHR_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_JURNAL_RIGHTS> LOGIN_JURNAL_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_NDOCS_RIGHTS> LOGIN_NDOCS_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_RIGHTS> LOGIN_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_SML_RIGHTS> LOGIN_SML_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_TJ_RIGHTS> LOGIN_TJ_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_UNIV_RIGHTS> LOGIN_UNIV_RIGHTS { get; set; }
        public virtual DbSet<LOGIN_UNIV2_RIGHTS> LOGIN_UNIV2_RIGHTS { get; set; }
        public virtual DbSet<METHPARVAR> METHPARVARS { get; set; }
        public virtual DbSet<REGNUM> REGNUMS { get; set; }
        public virtual DbSet<SMK2_JFORMS> SMK2_JFORMS { get; set; }
        public virtual DbSet<SMK2_JOURNALS> SMK2_JOURNALS { get; set; }
        public virtual DbSet<SML> SMLs { get; set; }
        public virtual DbSet<SPR_HEADERS> SPR_HEADERS { get; set; }
        public virtual DbSet<SPR_VALS> SPR_VALS { get; set; }
        public virtual DbSet<SR_DOC_ND> SR_DOC_ND { get; set; }
        public virtual DbSet<STATISTIKA> STATISTIKAs { get; set; }
        public virtual DbSet<UNIBOOK> UNIBOOKs { get; set; }
        public virtual DbSet<UNILAB> UNILABs { get; set; }
        public virtual DbSet<US> US { get; set; }
        public virtual DbSet<UZER> UZERs { get; set; }
        public virtual DbSet<UZERDB> UZERDBs { get; set; }
    }
}
