//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIBOOK
    {
        public int NUM_REC { get; set; }
        public string NAMEBOOK { get; set; }
        public string NAMEBOOKSM { get; set; }
        public Nullable<short> FORMTABLE { get; set; }
        public string DOP { get; set; }
        public Nullable<bool> HASTABLE { get; set; }
    }
}
