//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class US
    {
        public int NUM_REC { get; set; }
        public string NAM { get; set; }
        public string SNAM { get; set; }
        public Nullable<int> TYPVIEW { get; set; }
        public string DOP { get; set; }
        public Nullable<bool> EXPAND { get; set; }
        public Nullable<int> TYPUSE { get; set; }
        public byte[] DOCVIS { get; set; }
    }
}
