//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZER
    {
        public int NUM_USER { get; set; }
        public string NAME_SHORT { get; set; }
        public string NAME_FULL { get; set; }
        public string NAME_TINY { get; set; }
        public string NAME_MICRO { get; set; }
        public string SITY { get; set; }
        public string ADDR { get; set; }
        public string TELEFON { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CODES { get; set; }
        public string BANK { get; set; }
        public string DESCRIPTIONS { get; set; }
        public Nullable<short> OWNERMODE { get; set; }
        public Nullable<bool> PLUSCITY { get; set; }
        public string UROPT { get; set; }
        public Nullable<int> PASS_PER_ALERT { get; set; }
        public Nullable<int> PASS_BEHAVIOUR { get; set; }
    }
}
