//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTypeAttr
    {
        public int ID { get; set; }
        public int WorkTypeID { get; set; }
        public int AttrID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
