//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_time.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.AttrValues = new HashSet<AttrValue>();
        }
    
        public string WorkName { get; set; }
        public int ID { get; set; }
        public int TaskID { get; set; }
        public int WorkTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Minutes { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttrValue> AttrValues { get; set; }
        public virtual Task Task { get; set; }
        public virtual WorkType WorkType { get; set; }
        public virtual User User { get; set; }
    }
}
