//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTree.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropDataType
    {
        public System.Guid PropDataTypeID { get; set; }
        public System.Guid PropID { get; set; }
        public string DataValue { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
