//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTree.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTType
    {
        public System.Guid TaskTTypeID { get; set; }
        public System.Guid TaskID { get; set; }
        public System.Guid TTypeID { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TType TType { get; set; }
    }
}
